# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrisaktiConnect' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TrisaktiConnect

  pod 'React', :path => '../node_modules/react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-mail', :path => '../node_modules/react-native-mail'

end

target 'TrisaktiConnect-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TrisaktiConnect-tvOS

  target 'TrisaktiConnect-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
