export const SESSION = 'SESSION'
export const PROCESS_LOADING = 'PROCESS_LOADING'
export const PROCESS_FAILED = 'PROCESS_FAILED'
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const SET_LINK_NAVIGATE = 'SET_LINK_NAVIGATE'
export const SET_DATA_USER = 'SET_DATA_USER'

export const VOTE_LIST_ADDED = 'VOTE_LIST_ADDED'
export const REMOVE_LIST_SELECTED = 'REMOVE_LIST_SELECTED'

export const SEND_REPORT_REGISTER_SUCCESS = 'SEND_REPORT_REGISTER_SUCCESS'
export const SET_POSITION_TAB = 'SET_POSITION_TAB'

export const LOGIN_USER_SUCCESS_ID = 'LOGIN_USER_SUCCESS_ID'
export const LOGIN_USER_SUCCESS_TOKEN = 'LOGIN_USER_SUCCESS_TOKEN'
export const LOGIN_USER_LOADING = 'LOGIN_USER_LOADING'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS'
export const FETCH_NEWS_LOADING = 'FETCH_NEWS_LOADING'
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED'

export const FETCH_DATA_FACULTIES_SUCCESS = 'FETCH_DATA_FACULTIES_SUCCESS'
export const FETCH_DATA_FACULTIES_FAILED = 'FETCH_DATA_FACULTIES_FAILED'
export const FETCH_DATA_MAJORS_SUCCESS = 'FETCH_DATA_MAJORS_SUCCESS'
export const FETCH_DATA_MAJORS_FAILED = 'FETCH_DATA_MAJORS_FAILED'

export const FETCH_DATA_WITH_NIM_SUCCESS = 'FETCH_DATA_WITH_NIM_SUCCESS'
export const FETCH_DATA_WITH_NIM_FAILED = 'FETCH_DATA_WITH_NIM_FAILED'
export const FETCH_DATA_WITH_NIM_LOADING = 'FETCH_DATA_WITH_NIM_LOADING'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_LOADING = 'REGISTER_USER_LOADING'
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const PUBLISH_NEWS_SUCCESS = 'PUBLISH_NEWS_SUCCESS'
export const PUBLISH_NEWS_LOADING = 'PUBLISH_NEWS_LOADING'
export const PUBLISH_NEWS_FAILED = 'PUBLISH_NEWS_FAILED'

export const EDIT_PROFILE_USER_SUCCESS = 'EDIT_PROFILE_USER_SUCCESS'
export const EDIT_PROFILE_USER_LOADING = 'EDIT_PROFILE_USER_LOADING'
export const EDIT_RPOFILE_USER_FAILED = 'EDIT_RPOFILE_USER_FAILED'
export const CHANGE_PASSWORD_USER_SUCCESS = 'CHANGE_PASSWORD_USER_SUCCESS'
export const CHANGE_PASSWORD_USER_LOADING = 'CHANGE_PASSWORD_USER_LOADING'
export const CHANGE_PASSWORD_USER_FAILED = 'CHANGE_PASSWORD_USER_FAILED'

export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS'
export const SEND_COMMENT_LOADING = 'SEND_COMMENT_LOADING'
export const SEND_COMMENT_FAILED = 'SEND_COMMENT_FAILED'

export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS'
export const FETCH_COMMENT_LOADING = 'FETCH_COMMENT_LOADING'
export const FETCH_COMMENT_FAILED = 'FETCH_COMMENT_FAILED'

export const POST_ADD_CLAPS = 'POST_ADD_CLAPS'
export const POST_ADD_CLAPS_FAILED = 'POST_ADD_CLAPS_FAILED'

export const POST_JOB_SUCCESS = 'POST_JOB_SUCCESS'
export const POST_JOB_LOADING = 'POST_JOB_LOADING'
export const POST_JOB_FAILED = 'POST_JOB_FAILED'

export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS'
export const FETCH_JOB_LOADING = 'FETCH_JOB_LOADING'
export const FETCH_JOB_FAILED = 'FETCH_JOB_FAILED'

export const SEARCH_RESULT_USER = 'SEARCH_RESULT_USER'
export const SEARCH_RESULT_NEWS = 'SEARCH_RESULT_NEWS'
export const SEARCH_RESULT_VOTE = 'SEARCH_RESULT_VOTE'
export const SEARCH_RESULT_CAREER = 'SEARCH_RESULT_CAREER'
export const SEARCH_LOADING = 'SEARCH_LOADING'
export const SEARCH_NOTFOUND = 'SEARCH_NOTFOUND'
export const SEARCH_FAILED = 'SEARCH_FAILED'

export const SEND_REQUEST_FRIEND_SUCCESS = 'SEND_REQUEST_FRIEND_SUCCESS'
export const SEND_REQUEST_FRIEND_LOADING = 'SEND_REQUEST_FRIEND_LOADING'
export const SEND_REQUEST_FRIEND_FAILED = 'SEND_REQUEST_FRIEND_FAILED'

export const FETCH_FRIEND_REQUEST_SUCCESS = 'FETCH_FRIEND_REQUEST_SUCCESS'
export const FETCH_FRIEND_REQUEST_LOADING = 'FETCH_FRIEND_REQUEST_LOADING'
export const FETCH_FRIEND_REQUEST_FAILED = 'FETCH_FRIEND_REQUEST_FAILED'

export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS'
export const FETCH_FRIENDS_LOADING = 'FETCH_FRIENDS_LOADING'
export const FETCH_FRIENDS_FAILED = 'FETCH_FRIENDS_FAILED'

export const CONFIRM_FRIEND_REQUEST_SUCCESS = 'CONFIRM_FRIEND_REQUEST_SUCCESS'
export const CONFIRM_FRIEND_REQUEST_LOADING = 'CONFIRM_FRIEND_REQUEST_LOADING'
export const CONFIRM_FRIEND_REQUEST_FAILED = 'CONFIRM_FRIEND_REQUEST_FAILED'

export const REMOVE_FRIEND_REQUEST_SUCCESS = 'REMOVE_FRIEND_REQUEST_SUCCESS'
export const REMOVE_FRIEND_REQUEST_LOADING = 'REMOVE_FRIEND_REQUEST_LOADING'
export const REMOVE_FRIEND_REQUEST_FAILED = 'REMOVE_FRIEND_REQUEST_FAILED'

export const CHECK_FRIEND_STATUS = 'CHECK_FRIEND_STATUS'
export const CHECK_FRIEND_LOADING = 'CHECK_FRIEND_LOADING'
export const CHECK_FRIEND_FAILED = 'CHECK_FRIEND_FAILED'

export const CHECK_FRIEND_REQUEST_STATUS = 'CHECK_FRIEND_REQUEST_STATUS'
export const CHECK_FRIEND_REQUEST_LOADING = 'CHECK_FRIEND_REQUEST_LOADING'
export const CHECK_FRIEND_REQUEST_FAILED = 'CHECK_FRIEND_REQUEST_FAILED'

export const SEND_CHAT_PERSONAL_SUCCESS = 'SEND_CHAT_PERSONAL_SUCCESS'
export const SEND_CHAT_PERSONAL_LOADING = 'SEND_CHAT_PERSONAL_LOADING'
export const SEND_CHAT_PERSONAL_FAILED = 'SEND_CHAT_PERSONAL_FAILED'

export const FETCH_CHAT_PERSONAL_SUCCESS = 'FETCH_CHAT_PERSONAL_SUCCESS'
export const FETCH_CHAT_PERSONAL_LOADING = 'FETCH_CHAT_PERSONAL_LOADING'
export const FETCH_CHAT_PERSONAL_FAILED = 'FETCH_CHAT_PERSONAL_FAILED'

export const FETCH_CHAT_BY_ID_SUCCESS = 'FETCH_CHAT_BY_ID_SUCCESS'
export const FETCH_CHAT_BY_ID_LOADING = 'FETCH_CHAT_BY_ID_LOADING'
export const FETCH_CHAT_BY_ID_FAILED = 'FETCH_CHAT_BY_ID_FAILED'

export const FETCH_POLLS_SUCCESS = 'FETCH_POLLS_SUCCESS'
export const FETCH_POLLS_LOADING = 'FETCH_POLLS_LOADING'
export const FETCH_POLLS_FAILED = 'FETCH_POLLS_FAILED'

export const FETCH_POLLS_ANSWERS_SUCCESS = 'FETCH_POLLS_ANSWERS_SUCCESS'
export const FETCH_POLLS_ANSWERS_LOADING = 'FETCH_POLLS_ANSWERS_LOADING'
export const FETCH_POLLS_ANSWERS_FAILED = 'FETCH_POLLS_ANSWERS_FAILED'

export const CHECK_HAS_VOTED = 'CHECK_HAS_VOTED'

export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS'
export const POST_VOTE_LOADING = 'POST_VOTE_LOADING'
export const POST_VOTE_FAILED = 'POST_VOTE_FAILED'

export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS'
export const DELETE_CHAT_LOADING = 'DELETE_CHAT_LOADING'
export const DELETE_CHAT_FAILED = 'DELETE_CHAT_FAILED'